services:
  api-monitoramento:
    build: ./app/backend
    depends_on:
      - db-monitoramento
    container_name: api-monitoramento
    ports:
      - "8000:8000"
    volumes:
      - ./app/backend:/app
      - images:/app/static/images
    env_file:
      - path: ./app/backend/.env
        required: false
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
  
  db-monitoramento:
    image: postgres:15-alpine
    container_name: db-monitoramento
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: monitoramento    
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  
  frontend-react:
    build: ./app/frontend
    container_name: frontend-react
    ports:
      - "5173:5173"
    volumes:
      - ./app/frontend:/app
      - /app/node_modules
    depends_on:
      - api-monitoramento
    command: npm run dev -- --host

volumes:
  db_data:
  images: